version: 0.2
phases:
  install:
    commands:
      - cd Frontend
      - npm install
  pre_build:
    commands:
      - aws ssm get-parameter --name "/genwin/frontend/env/dev" --with-decryption --query "Parameter.Value" --output text > .env
      - aws ssm get-parameter --name "/genwin/frontend/env/sentry" --with-decryption --query "Parameter.Value" --output text > .env.sentry-build-plugin
  build:
    commands:
      - npm run build
      - ls -a
artifacts:
  files:
    - "**/*"
  base-directory: Frontend/dist
