version: 0.2

phases:
  install:
    commands:
      - npm ci

  build:
    commands:
      - npm run build:qa 

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync dist/ s3://genwin-frontend-qa-bucket --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E30EGNMUWCAXNR --paths "/*"

artifacts:
  files:
    - "**/*"
  base-directory: dist/ 