version: 0.2

env:
  variables:
    DEFAULT_ENV: "dev"
  shell: bash

phases:
  install:
    commands:
      - npm ci

  pre_build:
    commands:
      - echo "Detecting branch name..."
      - |
        if [ ! -z "$CODEBUILD_WEBHOOK_HEAD_REF" ]; then
          BRANCH_NAME=$(echo "$CODEBUILD_WEBHOOK_HEAD_REF" | sed 's|refs/heads/||')
        elif [[ "$CODEBUILD_SOURCE_VERSION" == refs/heads/* ]]; then
          BRANCH_NAME=$(echo "$CODEBUILD_SOURCE_VERSION" | sed 's|refs/heads/||')
        else
          BRANCH_NAME=${ENVIRONMENT:-"dev"}
        fi
      - echo $BRANCH_NAME

      - if [ "$BRANCH_NAME" = "dev" ]; then echo "BUILD_ENV=dev" > build_env.sh; fi
      - if [ "$BRANCH_NAME" = "qa" ]; then echo "BUILD_ENV=qa" > build_env.sh; fi
      - if [ ! -f build_env.sh ]; then echo "BUILD_ENV=dev" > build_env.sh; fi
      - source build_env.sh
      - echo "BUILD_ENV is set to $BUILD_ENV"

  build:
    commands:
      - echo $BUILD_ENV
      - npm run build:$BUILD_ENV
      - mkdir -p output/$BUILD_ENV
      - cp -r dist/* output/$BUILD_ENV/

artifacts:
  files:
    - "**/*"
  base-directory: output/
  discard-paths: no
