version: 0.2

phases:
  install:
    commands:
      - npm ci

  pre_build:
    commands:
      - echo "Extracting branch name..."
      - BRANCH_NAME=$(echo $CODEBUILD_SOURCE_VERSION | sed 's|refs/heads/||')
      - echo "Branch detected: $BRANCH_NAME"
      - if [[ "$BRANCH_NAME" == "dev" ]]; then export BUILD_ENV="dev"; fi
      - if [[ "$BRANCH_NAME" == "qa" ]]; then export BUILD_ENV="qa"; fi
      - if [[ -z "$BUILD_ENV" ]]; then echo "Unknown branch. Exiting..."; exit 1; fi
      - echo "BUILD_ENV set to: $BUILD_ENV"

  build:
    commands:
      - echo "Building for $BUILD_ENV..."
      - npm run build:$BUILD_ENV
      - echo "Build completed. Verifying dist/ folder..."
      - if [ ! -d "dist" ]; then echo "dist/ folder not found! Build failed."; exit 1; fi

  post_build:
    commands:
      - echo "Deploying to S3 in folder $BUILD_ENV..."
      - aws s3 sync dist/ s3://gen-win-frontend-bucket/$BUILD_ENV/ --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id EDTP3BU2RQEB --paths "/*"

artifacts:
  files:
    - "**/*"
  base-directory: dist/
