version: 0.2

phases:
  install:
    commands:
      - npm ci

  build:
    commands:
      - echo "Branch detected: $CODEBUILD_SOURCE_VERSION"
      - |
        if [[ "$CODEBUILD_SOURCE_VERSION" == "refs/heads/dev" ]]; then
          echo "Building for dev branch..."
          npm run build:dev
          export S3_FOLDER="dev"
        elif [[ "$CODEBUILD_SOURCE_VERSION" == "refs/heads/qa" ]]; then
          echo "Building for qa branch..."
          npm run build:qa
          export S3_FOLDER="qa"
        else
          echo "Unknown branch: $CODEBUILD_SOURCE_VERSION"
          exit 1
        fi
      - echo "Build completed. Verifying dist/ folder..."
      - ls -la dist/ || { echo "dist/ folder not found!"; exit 1; }

  post_build:
    commands:
      - echo "Deploying to S3 in folder $S3_FOLDER..."
      - aws s3 sync dist/ s3://gen-win-frontend-bucket/$S3_FOLDER/ --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id EDTP3BU2RQEB --paths "/*"

artifacts:
  files:
    - "**/*"
  base-directory: dist/
