version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - npm ci

  pre_build:
    commands:
      - echo "Extracting branch name..."
      - BRANCH_NAME=$(echo "$CODEBUILD_SOURCE_VERSION" | sed 's|refs/heads/||')
      - echo "Branch detected: $BRANCH_NAME"
      - |
        if [[ "$BRANCH_NAME" == "dev" ]]; then
          echo "BUILD_ENV=dev" >> build_env.sh;
        elif [[ "$BRANCH_NAME" == "qa" ]]; then
          echo "BUILD_ENV=qa" >> build_env.sh;
        else
          echo "Unknown branch. Exiting...";
          exit 1;
        fi
      - source build_env.sh
      - echo "BUILD_ENV is set to $BUILD_ENV"

  build:
    commands:
      - echo "Running build for environment: $BUILD_ENV"
      - npm run build:$BUILD_ENV

artifacts:
  files:
    - "**/*"
  base-directory: dist/