version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - npm ci

  pre_build:
    commands:
      - echo "Extracting branch name..."
      - BRANCH_NAME=$(echo "$CODEBUILD_SOURCE_VERSION" | sed 's|refs/heads/||')
      - echo "Branch detected: $BRANCH_NAME"
      - |
        if [[ "$BRANCH_NAME" == "dev" ]]; then
          echo "BUILD_ENV=dev" >> $CODEBUILD_ENV_VAR
        elif [[ "$BRANCH_NAME" == "qa" ]]; then
          echo "BUILD_ENV=qa" >> $CODEBUILD_ENV_VAR
        else
          echo "Unknown branch. Exiting..."
          exit 1
        fi
      - source $CODEBUILD_ENV_VAR
      - echo "BUILD_ENV is set to $BUILD_ENV"

  build:
    commands:
      - echo "Running build for environment: $BUILD_ENV"
      - npm run build:$BUILD_ENV
      - echo "Build complete. Checking artifacts..."
      - if [ ! -d "dist" ]; then echo "Error: dist folder missing!"; exit 1; fi

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 sync dist/ s3://gen-win-frontend-bucket/$BUILD_ENV/ --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id EDTP3BU2RQEB --paths "/*"

artifacts:
  files:
    - "**/*"
  base-directory: dist/
