export const countryData = [
  { label: "India", value: "India", code: "+91" },
  { label: "Australia", value: "Australia", code: "+61" },
  { label: "United Arab Emirates", value: "UAE", code: "+971" },
  { label: "New Zealand", value: "New_Zealand", code: "+64" },
];
export const statesByCountry = {
  India: [
    { label: "Andhra Pradesh", value: "AP" },
    { label: "Arunachal Pradesh", value: "AR" },
    { label: "Assam", value: "AS" },
    { label: "Bihar", value: "BR" },
    { label: "Chhattisgarh", value: "CG" },
    { label: "Goa", value: "GA" },
    { label: "Gujarat", value: "GJ" },
    { label: "Haryana", value: "HR" },
    { label: "Himachal Pradesh", value: "HP" },
    { label: "Jharkhand", value: "JH" },
    { label: "Karnataka", value: "KA" },
    { label: "Kerala", value: "KL" },
    { label: "Madhya Pradesh", value: "MP" },
    { label: "Maharashtra", value: "MH" },
    { label: "Manipur", value: "MN" },
    { label: "Meghalaya", value: "ML" },
    { label: "Mizoram", value: "MZ" },
    { label: "Nagaland", value: "NL" },
    { label: "Odisha", value: "OR" },
    { label: "Punjab", value: "PB" },
    { label: "Rajasthan", value: "RJ" },
    { label: "Sikkim", value: "SK" },
    { label: "Tamil Nadu", value: "TN" },
    { label: "Telangana", value: "TG" },
    { label: "Tripura", value: "TR" },
    { label: "Uttar Pradesh", value: "UP" },
    { label: "Uttarakhand", value: "UK" },
    { label: "West Bengal", value: "WB" },
  ],
  Australia: [
    { label: "New South Wales", value: "NSW" },
    { label: "Victoria", value: "VIC" },
    { label: "Queensland", value: "QLD" },
    { label: "Western Australia", value: "WA" },
    { label: "South Australia", value: "SA" },
    { label: "Tasmania", value: "TAS" },
    { label: "Australian Capital Territory", value: "ACT" },
    { label: "Northern Territory", value: "NT" },
  ],
  UAE: [
    { label: "Abu Dhabi", value: "AD" },
    { label: "Dubai", value: "DU" },
    { label: "Sharjah", value: "SH" },
    { label: "Ajman", value: "AJ" },
    { label: "Umm Al-Quwain", value: "UQ" },
    { label: "Ras Al Khaimah", value: "RK" },
    { label: "Fujairah", value: "FU" },
  ],
  New_Zealand: [
    { label: "Northland", value: "NL" },
    { label: "Auckland", value: "AK" },
    { label: "Waikato", value: "WK" },
    { label: "Bay of Plenty", value: "BP" },
    { label: "Gisborne", value: "GB" },
    { label: "Hawke's Bay", value: "HB" },
    { label: "Taranaki", value: "TK" },
    { label: "Manawatu-Wanganui", value: "MW" },
    { label: "Wellington", value: "WT" },
    { label: "Tasman", value: "TS" },
    { label: "Nelson", value: "NS" },
    { label: "Marlborough", value: "MB" },
    { label: "West Coast", value: "WC" },
    { label: "Canterbury", value: "CT" },
    { label: "Otago", value: "OT" },
    { label: "Southland", value: "SL" },
  ],
};
